global using Xunit;
global using AutoMapper;
global using dvg.Data.Entities;
global using dvg.Data.Repositories;
global using dvg.Data.Repositories.Interfaces;
global using dvg.Mappers;
global using dvg.Services;
global using dvg.Dto;
global using Moq;
